# Generated by Django 5.0.6 on 2024-10-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_title", models.CharField(max_length=255)),
                ("company_description", models.TextField()),
                ("company_logo", models.ImageField(upload_to="logos/")),
                ("job_title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("qualifications", models.TextField()),
                ("application_deadline", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="usertype",
            field=models.CharField(
                choices=[("recruiter", "Recruiter"), ("jobseeker", "Jobseeker")],
                max_length=100,
                null=True,
            ),
        ),
    ]
